# Minecraft / Loom
minecraft_version=1.21.10
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Mappings
yarn_mappings=1.21.10+build.1

# Fabric / API
fabric_version=0.100.11+1.21.10

# Project info
maven_group=com.montroller
archives_base_name=montroller
mod_version=1.0.0

# Gradle
java.toolchain.languageVersion=21
